
int absVal(int);
int test_absVal(int);
int addOK(int, int);
int test_addOK(int, int);
int allEvenBits();
int test_allEvenBits();
int bang(int);
int test_bang(int);
int bitAnd(int, int);
int test_bitAnd(int, int);
int bitMask(int, int);
int test_bitMask(int, int);
int bitXor(int, int);
int test_bitXor(int, int);
int byteSwap(int, int, int);
int test_byteSwap(int, int, int);
int conditional(int, int, int);
int test_conditional(int, int, int);
int copyLSB(int);
int test_copyLSB(int);
int ezThreeFourths(int);
int test_ezThreeFourths(int);
int fitsBits(int, int);
int test_fitsBits(int, int);
int getByte(int, int);
int test_getByte(int, int);
int isAsciiDigit(int);
int test_isAsciiDigit(int);
int isEqual(int, int);
int test_isEqual(int, int);
int isLess(int, int);
int test_isLess(int, int);
int isNonNegative(int);
int test_isNonNegative(int);
int isPower2(int);
int test_isPower2(int);
int isTmin(int);
int test_isTmin(int);
int minusOne();
int test_minusOne();
int rotateLeft(int, int);
int test_rotateLeft(int, int);
int satMul2(int);
int test_satMul2(int);
int subOK(int, int);
int test_subOK(int, int);

